name: tuple
version: 2.0.0

description: Tuple data structure
repository: https://github.com/google/tuple.dart

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
